<?php

namespace Database\Seeders;

use App\Models\Segment;
use App\Models\Type;
use Illuminate\Database\Seeder;

class TypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $typesData = [
            ['nama_type' => '1S7', 'segment' => 'CUB HIGH', 'nama_pasar' => 'YAMAHA JUPIETR MX 135 CC'],
            ['nama_type' => '3C1', 'segment' => 'SPORT MID', 'nama_pasar' => 'YAMAHA V-IXION 150 CC'],
            ['nama_type' => 'RX-K 135CC', 'segment' => 'CUB HIGH', 'nama_pasar' => 'YAMAHA RX-K 135 CC'],
            ['nama_type' => '45P', 'segment' => 'SPORT LOW', 'nama_pasar' => 'YAMAHA BYSON'],
            ['nama_type' => '31B', 'segment' => 'CUB MID', 'nama_pasar' => 'YAMAHA JUPITER Z'],
            ['nama_type' => '44D', 'segment' => 'AT HIGH', 'nama_pasar' => 'YAMAHA XEON'],
            ['nama_type' => '50S', 'segment' => 'CUB HIGH', 'nama_pasar' => 'YAMAHA JUPITER MX A/T'],
            ['nama_type' => '54D', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'YAMAHA SCORPIO'],
            ['nama_type' => '50C (T135HC) M/T', 'segment' => 'CUB HIGH', 'nama_pasar' => 'YAMAHA JUPIETR MX 135 CC Manual (CW)'],
            ['nama_type' => '55S (T135SEC) JUPITER MX', 'segment' => 'CUB HIGH', 'nama_pasar' => 'YAMAHA JUPIETR MX 135 AT CW'],
            ['nama_type' => '40D (TK 115) A/T', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'lexam'],
            ['nama_type' => '1 DY', 'segment' => 'CUB MID', 'nama_pasar' => 'JUPITER Z FI CW'],
            ['nama_type' => '1PA (V-IXION)', 'segment' => 'SPORT MID', 'nama_pasar' => 'VIXION'],
            ['nama_type' => '1 YD', 'segment' => 'AT MID', 'nama_pasar' => 'Mio Fino Sporty FI'],
            ['nama_type' => '1 LB', 'segment' => 'AT HIGH', 'nama_pasar' => 'XEON FI'],
            ['nama_type' => '2 DP', 'segment' => 'AT HIGH', 'nama_pasar' => 'NMAX'],
            ['nama_type' => '2 PK', 'segment' => 'SPORT MID', 'nama_pasar' => 'R 15'],
            ['nama_type' => '2 PV', 'segment' => 'CUB HIGH', 'nama_pasar' => 'YAMAHA JUPITER MX 150 KING'],
            ['nama_type' => '2PV', 'segment' => 'CUB HIGH', 'nama_pasar' => 'YAMAHA JUPITER MX 150 KING'],
            ['nama_type' => '2 SV', 'segment' => 'AT MID', 'nama_pasar' => 'GT 125 Eagle Eye'],
            ['nama_type' => '2 SX', 'segment' => 'AT MID', 'nama_pasar' => 'Mio Soul GT 125'],
            ['nama_type' => '2SX', 'segment' => 'AT MID', 'nama_pasar' => 'Mio Soul GT 125'],
            ['nama_type' => '2 TP', 'segment' => 'SPORT MID', 'nama_pasar' => 'New Vixion'],
            ['nama_type' => '2UP (BYSON R)', 'segment' => 'SPORT LOW', 'nama_pasar' => 'BYSON R'],
            ['nama_type' => '45P (BYSON)', 'segment' => 'SPORT LOW', 'nama_pasar' => 'BYSON R'],
            ['nama_type' => '2 BU AT (X-RIDE)', 'segment' => 'AT MID', 'nama_pasar' => 'X-RIDE'],
            ['nama_type' => '5D9 (VEGA RR)', 'segment' => 'CUB LOW', 'nama_pasar' => 'YAMAHA VEGA RR'],
            ['nama_type' => '54P (CAST WHEEL) A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'mio J ( FI ) CW'],
            ['nama_type' => 'B04', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'MT 25'],
            ['nama_type' => 'RG 10', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'R 25'],
            ['nama_type' => 'RG10', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'R 25'],
            ['nama_type' => 'SE88', 'segment' => 'AT LOW', 'nama_pasar' => 'Mio M3 CW'],
            ['nama_type' => 'SE 88', 'segment' => 'AT LOW', 'nama_pasar' => 'Mio M3 CW'],
            ['nama_type' => 'SE88 (Jari-Jari)', 'segment' => 'AT LOW', 'nama_pasar' => 'Mio M3 SP'],
            ['nama_type' => 'SE88 JARI-JARI', 'segment' => 'AT LOW', 'nama_pasar' => 'Mio M3 SP'],
            ['nama_type' => 'SE88 ( JARI - JARI )', 'segment' => 'AT LOW', 'nama_pasar' => 'Mio M3 SP'],
            ['nama_type' => 'UE 11 (CAST WELL)', 'segment' => 'CUB MID', 'nama_pasar' => 'JUPITER Z CW'],
            ['nama_type' => '2DP2', 'segment' => 'AT HIGH', 'nama_pasar' => 'NMAX'],
            ['nama_type' => '1 FD', 'segment' => 'CUB LOW', 'nama_pasar' => 'FORCE'],
            ['nama_type' => '1KP A/T (MIO SOUL)', 'segment' => 'AT LOW', 'nama_pasar' => 'MIO SOUL'],
            ['nama_type' => '1 FDC CAST WHEEL', 'segment' => 'CUB LOW', 'nama_pasar' => 'FORCE ELEGAN'],
            ['nama_type' => '1FDC CAST WHEEL', 'segment' => 'CUB LOW', 'nama_pasar' => 'Force'],
            ['nama_type' => '1FDC', 'segment' => 'CUB LOW', 'nama_pasar' => 'Force'],
            ['nama_type' => '1 FDC', 'segment' => 'CUB LOW', 'nama_pasar' => 'Force'],
            ['nama_type' => '1 LB (XEON RC)', 'segment' => 'AT HIGH', 'nama_pasar' => 'XEON FI'],
            ['nama_type' => 'BJ8', 'segment' => 'AT MID', 'nama_pasar' => 'NEW FINO BLUECORE'],
            ['nama_type' => 'BEI', 'segment' => 'AT HIGH', 'nama_pasar' => 'AEROX 125'],
            ['nama_type' => 'BE1', 'segment' => 'AT HIGH', 'nama_pasar' => 'AEROX 125'],
            ['nama_type' => 'BG7', 'segment' => 'SPORT MID', 'nama_pasar' => 'R15'],
            ['nama_type' => 'BN1', 'segment' => 'AT LOW', 'nama_pasar' => 'MIO Z'],
            ['nama_type' => '35D (VEGA ZR)', 'segment' => 'CUB LOW', 'nama_pasar' => 'VEGA ZR'],
            ['nama_type' => 'BN1  A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'MIO Z'],
            ['nama_type' => 'BU9', 'segment' => 'AT MID', 'nama_pasar' => 'Mio Soul GT 125'],
            ['nama_type' => 'B65 / AEROX 155 VVA', 'segment' => 'AT HIGH', 'nama_pasar' => 'Aerox 155'],
            ['nama_type' => 'B65-A', 'segment' => 'AT HIGH', 'nama_pasar' => 'Aerox 155'],
            ['nama_type' => 'BT2', 'segment' => 'AT MID', 'nama_pasar' => 'Mio Soul GT 125'],
            ['nama_type' => 'B65-R', 'segment' => 'AT HIGH', 'nama_pasar' => 'Aerox 155'],
            ['nama_type' => 'B65', 'segment' => 'AT HIGH', 'nama_pasar' => 'Aerox 155'],
            ['nama_type' => '54 P A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'MIO J'],
            ['nama_type' => 'BK6 R M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'All New Vixion R'],
            ['nama_type' => 'BK8  M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'All New Vixion'],
            ['nama_type' => 'BG6 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'XMAX'],
            ['nama_type' => 'by8', 'segment' => 'AT MID', 'nama_pasar' => 'xride'],
            ['nama_type' => 'BT3  M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'VIXION'],
            ['nama_type' => 'B3B A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'Mio S'],
            ['nama_type' => '1FDT', 'segment' => 'CUB LOW', 'nama_pasar' => 'vega force'],
            ['nama_type' => '2DP- R A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'NMAX ABS'],
            ['nama_type' => '2 DP R A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'NMAX ABS'],
            ['nama_type' => '2DP RA A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'NMAX Non ABS'],
            ['nama_type' => '2DP- RA A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'NMAX Non ABS'],
            ['nama_type' => '2DP', 'segment' => 'AT HIGH', 'nama_pasar' => 'NMAX ABS'],
            ['nama_type' => '2DP NON ABS', 'segment' => 'AT HIGH', 'nama_pasar' => 'NMAX Non ABS'],
            ['nama_type' => 'BJ8 W A/T', 'segment' => 'AT MID', 'nama_pasar' => 'Fino FI 125 Premium'],
            ['nama_type' => 'BY8 A/T', 'segment' => 'AT MID', 'nama_pasar' => 'xride'],
            ['nama_type' => 'BT2 W A/T', 'segment' => 'AT MID', 'nama_pasar' => 'Mio Soul GT 125'],
            ['nama_type' => 'B3F-I A/T', 'segment' => 'AT MID', 'nama_pasar' => 'LEXI'],
            ['nama_type' => 'B3F-F A/T', 'segment' => 'AT MID', 'nama_pasar' => 'LEXI'],
            ['nama_type' => 'NEW FINO SPORTY 125', 'segment' => 'AT MID', 'nama_pasar' => 'NEW FINO SPORTY 125'],
            ['nama_type' => 'UE11 (CAST WHEEL)', 'segment' => 'CUB MID', 'nama_pasar' => 'Jupiter Z1 CW FI'],
            ['nama_type' => 'NF11T11 CO1 M/T', 'segment' => 'CUB LOW', 'nama_pasar' => 'NEW REVO FIT MMC'],
            ['nama_type' => 'NF11T11C01 M/T', 'segment' => 'CUB LOW', 'nama_pasar' => 'NEW REVO FIT MMC'],
            ['nama_type' => 'NF11T13C02 M/T', 'segment' => 'CUB LOW', 'nama_pasar' => 'REVO SW MMC'],
            ['nama_type' => 'NF11T14C03 M/T', 'segment' => 'CUB LOW', 'nama_pasar' => 'NEW REVO X'],
            ['nama_type' => 'AFP12W21C03 M/T', 'segment' => 'CUB MID', 'nama_pasar' => 'BLADE S 125 FI'],
            ['nama_type' => 'AFP12W21C08 M/T', 'segment' => 'CUB MID', 'nama_pasar' => 'NEW BLADE 125 FI R STANDARD'],
            ['nama_type' => 'AFP12W22C08A M/T', 'segment' => 'CUB MID', 'nama_pasar' => 'NEW BLADE 125 FI R REPSOL EDITION'],
            ['nama_type' => 'AFX12U21 C07 M/T', 'segment' => 'CUB MID', 'nama_pasar' => 'SUPRA X 125 SW'],
            ['nama_type' => 'AFX12U21C08 M/T', 'segment' => 'CUB MID', 'nama_pasar' => 'SUPRA X 125 CW'],
            ['nama_type' => 'AFX12U22C08A M/T', 'segment' => 'CUB MID', 'nama_pasar' => 'NEW SUPRA X 125 CW FI MMC - LUXURY'],
            ['nama_type' => 'NF12A1CF3 M/T', 'segment' => 'CUB MID', 'nama_pasar' => 'SUPRA HELM IN FI MMC'],
            ['nama_type' => 'G2E02R21L0 M/T', 'segment' => 'CUB HIGH', 'nama_pasar' => 'New Supra GTR150 Sporty'],
            ['nama_type' => 'G2E02R21S2A M/T', 'segment' => 'CUB HIGH', 'nama_pasar' => 'New Supra GTR150 Exclusive'],
            ['nama_type' => 'Y1G02N02 L 0 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'BEAT POP ESP CW'],
            ['nama_type' => 'Y1G02N02L1A A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'NEW BEAT POP ESP CW COMIC'],
            ['nama_type' => 'Y1G02N02S1AA A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'BEAT POP ESP CBS'],
            ['nama_type' => 'Y1G02N02L1AB A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'NEW BEAT POP ESP CBS COMIC'],
            ['nama_type' => 'Y1G02N15L0 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'BEAT POP ESP CBS ISS'],
            ['nama_type' => 'Y1G02N15L1A A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'NEW BEAT POP ESP CBS ISS COMIC'],
            ['nama_type' => 'D1B02N26L2 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'BEAT SPORTY CW'],
            ['nama_type' => 'D1B02N12L2 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'BEAT SPORTY CBS'],
            ['nama_type' => 'D1B02N13L2 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'BEAT SPORTY CBS ISS'],
            ['nama_type' => 'D1I02N27S3 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'BEAT STREET Matte Black'],
            ['nama_type' => 'NC11D1CF2 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'SPACY HELM IN FI MMC'],
            ['nama_type' => 'V1J02Q32L0 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'NEW PCX 150 CBS'],
            ['nama_type' => 'V1J02Q33L0 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'NEW PCX 150 ABS'],
            ['nama_type' => 'D1A02N18M1 A/T', 'segment' => 'AT MID', 'nama_pasar' => 'New Vario 110 FI CBS MMC'],
            ['nama_type' => 'D1A02N18S2A A/T', 'segment' => 'AT MID', 'nama_pasar' => 'New Vario 110 FI CBS Advanced MMC'],
            ['nama_type' => 'D1A02N19M1 A/T', 'segment' => 'AT MID', 'nama_pasar' => 'New Vario 110 FI CBS ISS MMC'],
            ['nama_type' => 'D1A02N19S2A A/T', 'segment' => 'AT MID', 'nama_pasar' => 'New Vario 110 FI CBS – ISS Advanced MMC'],
            ['nama_type' => 'A1F02N36M1 A/T', 'segment' => 'AT MID', 'nama_pasar' => 'VARIO 125 CBS'],
            ['nama_type' => 'A1F02N37M1 A/T', 'segment' => 'AT MID', 'nama_pasar' => 'VARIO 125 CBS ISS'],
            ['nama_type' => 'K1H02N14L0 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'NEW VARIO 150 - SPORTY'],
            ['nama_type' => 'X1H02N35M1 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'VARIO 150'],
            ['nama_type' => 'B5D02K29M2 M/T', 'segment' => 'SPORT LOW', 'nama_pasar' => 'New CB150 Verza SW'],
            ['nama_type' => 'B5D02M29M2 M/T', 'segment' => 'SPORT LOW', 'nama_pasar' => 'New CB150 Verza CW'],
            ['nama_type' => 'A5C02R37M2C M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'CB150R Streetfire'],
            ['nama_type' => 'A5C02R37M2B M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'CB150R Streetfire'],
            ['nama_type' => 'A5C02R37M2A M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'CB150R Streetfire'],
            ['nama_type' => 'A5C02R37M2 M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'CB150R Streetfire'],
            ['nama_type' => 'Y3B02RI7LO M/T', 'segment' => 'SPORT LOW', 'nama_pasar' => 'SONIC 150R'],
            ['nama_type' => 'Y3B02R17S3A M/T', 'segment' => 'SPORT LOW', 'nama_pasar' => 'SONIC 150R HRR'],
            ['nama_type' => 'Y3B02R17S3B M/T', 'segment' => 'SPORT LOW', 'nama_pasar' => 'SONIC 150R MATTE BLACK'],
            ['nama_type' => 'L1K02Q34L0 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'PCX Hybrid'],
            ['nama_type' => 'R5F04R25S1 M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'New CBR250RR STD'],
            ['nama_type' => 'R5F04R25S1B M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'New CBR250RR STD'],
            ['nama_type' => 'R5F04R25S1C M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'New CBR250RR STD'],
            ['nama_type' => 'R5F04R24S1 M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'New CBR250RR ABS'],
            ['nama_type' => 'R5F04R24S1A M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'New CBR250RR ABS'],
            ['nama_type' => 'R5F04R24S1B M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'New CBR250RR ABS'],
            ['nama_type' => 'P5E02R22M2 M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'CBR150R STD'],
            ['nama_type' => 'P5E02R22M2A M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'CBR150R STD'],
            ['nama_type' => 'P5E02R22M2B M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'CBR150R STD'],
            ['nama_type' => 'CRF250RLI IN M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'CRF250RALLY'],
            ['nama_type' => 'R5F04R25S1A M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'New CBR250RR STD'],
            ['nama_type' => 'F1C02N28S1A A/T', 'segment' => 'AT MID', 'nama_pasar' => 'All New Scoopy Stylish'],
            ['nama_type' => 'F1C02N28S1B A/T', 'segment' => 'AT MID', 'nama_pasar' => 'All New Scoopy Sporty'],
            ['nama_type' => 'F1C02N28L0 A/T', 'segment' => 'AT MID', 'nama_pasar' => 'All New Scoopy Playful'],
            ['nama_type' => 'SH150ADH IN A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'SH150i'],
            ['nama_type' => 'R5F04R25L0 M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'New CBR 250RR ABS'],
            ['nama_type' => 'T4G02T31S1 M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'CRF150L'],
            ['nama_type' => 'T4G02T31L0 M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'CRF150L'],
            ['nama_type' => 'G2E02R21S2 M/T', 'segment' => 'CUB HIGH', 'nama_pasar' => 'New Supra GTR150 Sporty'],
            ['nama_type' => 'AFX12U24C08 M/T', 'segment' => 'CUB MID', 'nama_pasar' => 'SUPRA X 125 CW'],
            ['nama_type' => 'D1B02N12S2 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'BEAT SPORTY CBS'],
            ['nama_type' => 'C125K IN M/T', 'segment' => 'CUB HIGH', 'nama_pasar' => 'New Supercub C125'],
            ['nama_type' => 'P5E02R22M1 M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'CBR150R ABS'],
            ['nama_type' => 'P5E02R40M2A M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'CBR150R ABS'],
            ['nama_type' => 'P5E02R40M2B M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'CBR150R ABS'],
            ['nama_type' => 'R5F04R24L0 M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'New CBR 250RR ABS'],
            ['nama_type' => 'NSS250AJ IN A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'FORZA'],
            ['nama_type' => 'GL15B1DF M/T', 'segment' => 'SPORT LOW', 'nama_pasar' => 'Verza'],
            ['nama_type' => 'GL15C21A07 M/T', 'segment' => 'SPORT LOW', 'nama_pasar' => 'Mega Pro'],
            ['nama_type' => 'H5C02R20M1 M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'CB150R Streetfire'],
            ['nama_type' => 'KAISAR TRISEDA (RODA 3)', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'Uncategory'],
            ['nama_type' => 'TM 200 ZH M/T', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'Uncategory'],
            ['nama_type' => 'LX150h', 'segment' => 'SPORT MID', 'nama_pasar' => 'KLX 150'],
            ['nama_type' => 'LX150G', 'segment' => 'SPORT MID', 'nama_pasar' => 'KLX 150'],
            ['nama_type' => 'LX150F', 'segment' => 'SPORT MID', 'nama_pasar' => 'KLX 150'],
            ['nama_type' => 'LX150F VARIAN 1', 'segment' => 'SPORT MID', 'nama_pasar' => 'KLX 150'],
            ['nama_type' => 'BJ175A', 'segment' => 'SPORT MID', 'nama_pasar' => 'W175'],
            ['nama_type' => 'D1I02N27S2 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'BEAT STREET CBS'],
            ['nama_type' => 'B5D-I A/T', 'segment' => 'AT MID', 'nama_pasar' => 'Free GO'],
            ['nama_type' => 'B5D-IA A/T', 'segment' => 'AT MID', 'nama_pasar' => 'Free GO'],
            ['nama_type' => 'B5D A/T', 'segment' => 'AT MID', 'nama_pasar' => 'Free GO'],
            ['nama_type' => 'Y1G02N02L0 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'BEAT POP ESP CW'],
            ['nama_type' => 'RG10 S M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'R 25'],
            ['nama_type' => 'TM150 ZH M/T', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'Uncategory'],
            ['nama_type' => 'HP 125-B', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'Uncategory'],
            ['nama_type' => 'LX150E CKD', 'segment' => 'SPORT MID', 'nama_pasar' => 'KLX 150'],
            ['nama_type' => 'EX 250S', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Ninja 250'],
            ['nama_type' => 'EX250T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Ninja 250'],
            ['nama_type' => 'LX250V', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'KLX 250'],
            ['nama_type' => 'AZABU (200CC)', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'Uncategory'],
            ['nama_type' => 'SPRINT IGET 150 ABS A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'Vespa'],
            ['nama_type' => 'PRIMAVERA IGET 150 ABS', 'segment' => 'AT HIGH', 'nama_pasar' => 'Vespa Primavera'],
            ['nama_type' => 'V 15 RL', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'Uncategory'],
            ['nama_type' => 'V 20 RL', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'Uncategory'],
            ['nama_type' => 'V 20 T', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'Uncategory'],
            ['nama_type' => 'V 30 R', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'Uncategory'],
            ['nama_type' => 'V 10 R', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'Uncategory'],
            ['nama_type' => 'VR 150 3R', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'Uncategory'],
            ['nama_type' => 'VR 200 3R', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'Uncategory'],
            ['nama_type' => 'Y3B02R17L0 M/T', 'segment' => 'SPORT LOW', 'nama_pasar' => 'SONIC 150R'],
            ['nama_type' => 'UX 110', 'segment' => 'AT LOW', 'nama_pasar' => 'Nex CW FI'],
            ['nama_type' => 'FV 110 LE', 'segment' => 'CUB LOW', 'nama_pasar' => 'Shooter FI'],
            ['nama_type' => 'GSX  R150', 'segment' => 'SPORT MID', 'nama_pasar' => 'GSX  R150'],
            ['nama_type' => '2PV R M/T', 'segment' => 'CUB HIGH', 'nama_pasar' => 'YAMAHA JUPITER MX 150 KING'],
            ['nama_type' => 'AFP12W21CO8 M/T', 'segment' => 'CUB MID', 'nama_pasar' => 'NEW BLADE 125 FI R STANDARD'],
            ['nama_type' => 'VESPA LX IGET 125 3V ie A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'Vespa LX'],
            ['nama_type' => 'BX 250 A', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Ninja 250'],
            ['nama_type' => 'UK 110 NE', 'segment' => 'AT LOW', 'nama_pasar' => 'Adress'],
            ['nama_type' => 'NF12A1CF M/T', 'segment' => 'CUB MID', 'nama_pasar' => 'SUPRA 125'],
            ['nama_type' => 'AFX12U21C07 M/T', 'segment' => 'CUB MID', 'nama_pasar' => 'SUPRA X 125 SW'],
            ['nama_type' => 'VESPA S IGET 125 3V IE A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'Vespa LX'],
            ['nama_type' => 'BG7 M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'R15'],
            ['nama_type' => 'BR125H', 'segment' => 'SPORT LOW', 'nama_pasar' => 'Max 125'],
            ['nama_type' => 'B8D M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'Xabre'],
            ['nama_type' => 'AFP12W21CO3 M/T', 'segment' => 'CUB MID', 'nama_pasar' => 'BLADE S 125 FI'],
            ['nama_type' => 'EX250X', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Ninja 250'],
            ['nama_type' => 'BJ175B', 'segment' => 'SPORT MID', 'nama_pasar' => 'W175'],
            ['nama_type' => '2DP NON ABS', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'UNCATEGORY'],
            ['nama_type' => '2BU', 'segment' => 'AT MID', 'nama_pasar' => 'XRIDE'],
            ['nama_type' => 'FU 150', 'segment' => 'SPORT LOW', 'nama_pasar' => 'Satria Fu'],
            ['nama_type' => 'PRIMAVERA IGET 150 ABS A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'PRIMAVERA IGET 150 ABS A/T'],
            ['nama_type' => 'EX250W', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Ninja 250'],
            ['nama_type' => 'C1M02N41L0 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'GENIO CBS'],
            ['nama_type' => 'X1N02Q43L0 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'ADV CBS'],
            ['nama_type' => 'X1N02Q44L0 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'ADV CBS ISS'],
            ['nama_type' => 'C1M02N42L0 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'GENIO CBS ISS'],
            ['nama_type' => 'LX250S', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'LX250S'],
            ['nama_type' => 'B3F-FA A/T', 'segment' => 'AT MID', 'nama_pasar' => 'LEXI'],
            ['nama_type' => 'LX230B', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'LX230B'],
            ['nama_type' => 'UE11', 'segment' => 'CUB MID', 'nama_pasar' => 'Jupiter Z1 CW FI'],
            ['nama_type' => 'H1B02N41L0 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'Beat Sporty'],
            ['nama_type' => 'H1B02N42L0 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'BEAT SPORTY CBS ISS'],
            ['nama_type' => 'Z125MAK ED M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Monkey'],
            ['nama_type' => 'LX150J', 'segment' => 'SPORT MID', 'nama_pasar' => 'LX150J'],
            ['nama_type' => '2PK', 'segment' => 'SPORT MID', 'nama_pasar' => 'R15 Special Edition'],
            ['nama_type' => 'BBS M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'WR 155 R'],
            ['nama_type' => 'B9T M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'New MT 25'],
            ['nama_type' => 'B6H A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'New Nmax  CBS'],
            ['nama_type' => 'LX230D', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'KLX230'],
            ['nama_type' => 'CMX500AK IN M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Rebel'],
            ['nama_type' => 'BJ175C', 'segment' => 'SPORT MID', 'nama_pasar' => 'W175'],
            ['nama_type' => 'GT 125 (2SV)', 'segment' => 'AT MID', 'nama_pasar' => 'GT 125 (2SV)'],
            ['nama_type' => 'B6H-AI A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'New Nmax  ABS'],
            ['nama_type' => 'B3M M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'WR 155 R'],
            ['nama_type' => 'CBR1000RAJ 2IN M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'CBR 1000'],
            ['nama_type' => 'GSF-150', 'segment' => 'SPORT MID', 'nama_pasar' => 'GSF-150'],
            ['nama_type' => 'ZX250G', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Kawasaki Ninja'],
            ['nama_type' => 'UX110', 'segment' => 'AT LOW', 'nama_pasar' => 'New Suzuki Nex'],
            ['nama_type' => 'ZX250F', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Kawasaki Ninja'],
            ['nama_type' => 'CRF250 RLK IN M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'CRF 250 rally'],
            ['nama_type' => 'R5F04R24L1 M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'CBR 250 RR'],
            ['nama_type' => 'BBP A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'Aerox 155'],
            ['nama_type' => 'BBP-A A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'Aerox 155'],
            ['nama_type' => 'F1C02N46L0 A/T', 'segment' => 'AT MID', 'nama_pasar' => 'New Scoopy'],
            ['nama_type' => 'B3W A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'Gear 125'],
            ['nama_type' => 'UE11 CAST WHEEL', 'segment' => 'CUB MID', 'nama_pasar' => 'Zupiter'],
            ['nama_type' => 'B6H-F A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'New Nmax  ABS'],
            ['nama_type' => 'ECONOS', 'segment' => 'SPORT LOW', 'nama_pasar' => 'ECONOS'],
            ['nama_type' => 'B3W-S A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'Gear 125 S'],
            ['nama_type' => 'VESPA S IGET 125 FL A/T', 'segment' => 'UNCATEGORY', 'nama_pasar' => 'UNCATEGORY'],
            ['nama_type' => 'V1J02Q50L1 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'PCX160 ABS'],
            ['nama_type' => 'V1J02Q32L1 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'PCX160 CBS'],
            ['nama_type' => 'BJ250L', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'BJ250L'],
            ['nama_type' => 'P5E02R48L0 M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'New CBR150RR'],
            ['nama_type' => 'B6H-A A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'New Nmax  ABS'],
            ['nama_type' => 'SPRINT IGET 150 ABS', 'segment' => 'AT HIGH', 'nama_pasar' => 'Vespa Spring'],
            ['nama_type' => 'P5E02R49L0 M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'New CBR150RR'],
            ['nama_type' => 'LE250E', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Kawasaki Versys'],
            ['nama_type' => 'BG6-I A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'New Nmax  ABS'],
            ['nama_type' => 'R5F04R25L1 M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'CBR 250 RR'],
            ['nama_type' => 'L1K02Q51L0 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'PCX 160 Hybrid'],
            ['nama_type' => 'UK110NE', 'segment' => 'AT LOW', 'nama_pasar' => 'Address'],
            ['nama_type' => 'GL200 D', 'segment' => 'SPORT MID', 'nama_pasar' => 'New CB150RR'],
            ['nama_type' => 'A5C02R52L1 M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'New CB150RR'],
            ['nama_type' => 'G1', 'segment' => 'AT HIGH', 'nama_pasar' => 'GESITS'],
            ['nama_type' => '2UP', 'segment' => 'SPORT LOW', 'nama_pasar' => 'BYSON R'],
            ['nama_type' => 'NSS250AM IN A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'FORZA'],
            ['nama_type' => 'C125N IN M/T', 'segment' => 'CUB HIGH', 'nama_pasar' => 'C125N IN M/T'],
            ['nama_type' => 'T5C02R37L0 M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'CB150X'],
            ['nama_type' => 'ZXT02L', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Kawasaki'],
            ['nama_type' => 'ER250C', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'ER250C'],
            ['nama_type' => 'BBS-R M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'Yamahan XRS 155'],
            ['nama_type' => 'BEJ A/T', 'segment' => 'AT MID', 'nama_pasar' => 'FAZIO'],
            ['nama_type' => 'X1H02N32L1 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'Vario 160 CBS'],
            ['nama_type' => 'L1K02Q33L1 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'Vario 160 ABS'],
            ['nama_type' => 'BDJ M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'Yamaha R15'],
            ['nama_type' => 'CMX500AM IN M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Rebel'],
            ['nama_type' => 'C1M02N41L1 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'Genio CBS'],
            ['nama_type' => 'C1M02N42L1 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'Genio CBS ISS'],
            ['nama_type' => 'C125N 2IN M/T', 'segment' => 'CUB HIGH', 'nama_pasar' => 'C125'],
            ['nama_type' => 'BDJ-A M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'Yamaha R15'],
            ['nama_type' => 'N1N02Q43L1 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'ADV 160'],
            ['nama_type' => 'CRF250LRM IN M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'CRF250RR'],
            ['nama_type' => 'L1F02N36L1 A/T', 'segment' => 'AT MID', 'nama_pasar' => 'VARIO 125 CBS (NEW 2022)'],
            ['nama_type' => 'L1F02N37L1 A/T', 'segment' => 'AT MID', 'nama_pasar' => 'VARIO 125 CBS ISS (NEW 2022)'],
            ['nama_type' => 'ZX250J', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Kawasaki Ninja ZX-25R'],
            ['nama_type' => 'LX230P', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Kawasaki KLX 130'],
            ['nama_type' => 'ZX250K', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Kawasaki Ninja ZX-25R'],
            ['nama_type' => 'R5F04R24L3 M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'CBR 250 QS'],
            ['nama_type' => 'B8D-R M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'XABRE'],
            ['nama_type' => 'R5F04R25L3 M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'CBR 250 QS'],
            ['nama_type' => 'LX230V', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'LX230V'],
            ['nama_type' => 'BKU A/T', 'segment' => 'AT MID', 'nama_pasar' => 'Free GO'],
            ['nama_type' => 'BKU S A/T', 'segment' => 'AT MID', 'nama_pasar' => 'Free GO'],
            ['nama_type' => 'BPV A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'XMAX'],
            ['nama_type' => 'BJM A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'FILANO'],
            ['nama_type' => 'BT3-R M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'Vixion'],
            ['nama_type' => 'LX150M', 'segment' => 'SPORT MID', 'nama_pasar' => 'LX150M'],
            ['nama_type' => 'LX150K', 'segment' => 'SPORT MID', 'nama_pasar' => 'LX150K'],
            ['nama_type' => 'FU150', 'segment' => 'SPORT MID', 'nama_pasar' => 'Satria Fu'],
            ['nama_type' => 'Z125MAN 2IN M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Monkey'],
            ['nama_type' => 'LX150L', 'segment' => 'SPORT MID', 'nama_pasar' => 'LX150K'],
            ['nama_type' => 'N1N02Q33L1 A/T', 'segment' => 'AT High', 'nama_pasar' => 'ADV 160 ABS'],
            ['nama_type' => 'RG10 SA M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Yamaha MT 25'],
            ['nama_type' => 'EX252A', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Kawawaki'],
            ['nama_type' => 'BBP-L A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'Aerox'],
            ['nama_type' => 'B6H-L A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'New Nmax  ABS'],
            ['nama_type' => 'BJM-L A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'FILANO'],
            ['nama_type' => 'BEJ-L A/T', 'segment' => 'AT MID', 'nama_pasar' => 'FAZIO'],
            ['nama_type' => 'L1F02N36L1 A/T', 'segment' => 'AT MID', 'nama_pasar' => 'VARIO 125 CBS (NEW 2022)'],
            ['nama_type' => 'CRF250LP IN M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'CRF 250 rally'],
            ['nama_type' => 'NSS250AP IN A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'FORZA'],
            ['nama_type' => 'CRF250LRP IN M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'CRF 250 R'],
            ['nama_type' => 'BPV-T A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'XMAX'],
            ['nama_type' => 'BPN-L A/T', 'segment' => 'AT MID', 'nama_pasar' => 'LEXI'],
            ['nama_type' => 'M1K03M32L0 AT', 'segment' => 'AT HIGH', 'nama_pasar' => 'STYLO CBS'],
            ['nama_type' => 'M1K03Q33L0 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'STYLO ABS'],
            ['nama_type' => 'BPN-A A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'LEXI'],
            ['nama_type' => 'BPN-SL A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'LEXI'],
            ['nama_type' => 'CB650RAP 2IN M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'CBR 650'],
            ['nama_type' => 'H1B02N42L1 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'BeAT Sporty CBS ISS Deluxe (2024)'],
            ['nama_type' => 'H1B02N41L1 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'BeAT Sporty CBS (2024)'],
            ['nama_type' => 'H1B02N53L1 A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'BeAT Street (2024)'],
            ['nama_type' => 'BTE A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'NMAX NEO 2 2024'],
            ['nama_type' => 'BTD A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'NMAX TURBO 2024'],
            ['nama_type' => 'BLS A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'NMAX TURBO TECH MAX 2024'],
            ['nama_type' => 'BPA A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'NMAX  NEO 2024'],
            ['nama_type' => 'ZX636J', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'ZX636J'],
            ['nama_type' => 'F1C02N46L2 A/T', 'segment' => 'AT MID', 'nama_pasar' => 'New Scoopy ( 2024 )'],
            ['nama_type' => 'BEJ-I A/T', 'segment' => 'AT MID', 'nama_pasar' => 'FAZIO'],
            ['nama_type' => 'BEJ-C A/T', 'segment' => 'AT MID', 'nama_pasar' => 'FAZIO'],
            ['nama_type' => 'BJ175D', 'segment' => 'SPORT MID', 'nama_pasar' => 'W175'],
            ['nama_type' => 'C125S 2IN M/T', 'segment' => 'CUB HIGH', 'nama_pasar' => 'C125'],
            ['nama_type' => 'V1J02Q54L0 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'PCX160 RoadSync'],
            ['nama_type' => 'V1J02Q32L2 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'PCX160 CBS'],
            ['nama_type' => 'V1J02Q50L2 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'PCX160 ABS'],
            ['nama_type' => 'D09 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'New Aerox 155'],
            ['nama_type' => 'D09-A A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'New Aerox 155'],
            ['nama_type' => 'BWP A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'New Aerox Alpha Turbo'],
            ['nama_type' => 'BXY A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'GEAR ULTIMA'],
            ['nama_type' => 'BXY-K A/T', 'segment' => 'AT LOW', 'nama_pasar' => 'GEAR ULTIMA'],
            ['nama_type' => 'BPN-S A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'LEXI'],
            ['nama_type' => 'BPN A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'LEXI'],
            ['nama_type' => 'N1N02Q54L2 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'ADV 160 ROADSYNC'],
            ['nama_type' => 'N1N02Q43L2 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'ADV 160 CBS'],
            ['nama_type' => 'N1N02Q33L2 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'ADV160 ABS'],
            ['nama_type' => 'CRF250LRAS IN M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'CRF250LRAS IN M/T'],
            ['nama_type' => 'LX232F', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'LX'],
            ['nama_type' => 'CRF250LAS IN M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'CRF250LAS IN M/T'],
            ['nama_type' => 'L1F02N37L2 A/T', 'segment' => 'AT MID', 'nama_pasar' => 'VARIO 125 CBS ISS'],
            ['nama_type' => 'L1F02N36L2 A/T', 'segment' => 'AT MID', 'nama_pasar' => 'VARIO 125 CBS'],
            ['nama_type' => 'L1F02N53L2 A/T', 'segment' => 'AT MID', 'nama_pasar' => 'VARIO 125 Street'],
            ['nama_type' => 'CMX500AS IN M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Rebel'],
            ['nama_type' => 'MONKEY', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Monkey'],
            ['nama_type' => 'DAX 125 TAMIYA', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'DAX'],
            ['nama_type' => 'BPV-D A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'XMAX'],
            ['nama_type' => 'M1K03M32L0 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'New Stylo 2026'],
            ['nama_type' => 'BXY-I A/T', 'segment' => 'AT MID', 'nama_pasar' => 'Free GO'],
            ['nama_type' => 'B3M-E M/T', 'segment' => 'SPORT MID', 'nama_pasar' => 'WR 155 R'],
            ['nama_type' => 'BRJ M/T', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'MT-25'],
            ['nama_type' => 'BKU-S A/T', 'segment' => 'AT MID', 'nama_pasar' => 'Free GO'],
            ['nama_type' => 'TZR 3MA', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'TZR'],
            ['nama_type' => 'LX232Y', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'KLX230'],
            ['nama_type' => 'BJ175J', 'segment' => 'SPORT MID', 'nama_pasar' => 'W175'],
            ['nama_type' => 'LE250F', 'segment' => 'SPORT HIGH', 'nama_pasar' => 'Versys-X 250'],
            ['nama_type' => 'X1H02Q33L3 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'VARIO EVO 160 ABS'],
            ['nama_type' => 'X1H02N32L3 A/T', 'segment' => 'AT HIGH', 'nama_pasar' => 'VARIO EVO 160 CBS NITRO'],
        ];

        foreach ($typesData as $item) {
            $segmentName = strtoupper(trim($item['segment']));
            $segment = Segment::firstOrCreate(['nama_segment' => $segmentName]);

            Type::create([
                'nama_type' => trim($item['nama_type']),
                'segment_id' => $segment->id,
                'nama_pasar' => trim($item['nama_pasar']),
            ]);
        }
    }
}
